In [201]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score as r2
from sklearn.metrics import mean_squared_error as mse
from sklearn.model_selection import train_test_split

In [257]:
data = pd.read_csv('train.csv')

In [258]:
data.head()

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
0  14038          35    2.0  47.981561   29.442751            6.0      7   
1  15053          41    3.0  65.683640   40.049543            8.0      7   
2   4765          53    2.0  44.947953   29.197612            0.0      8   
3   5809          58    2.0  53.352981   52.731512            9.0      8   
4  10783          99    1.0  39.649192   23.776169            7.0     11   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0         9.0       1969   0.089040         B         B        33      7976   
1         9.0       1978   0.000070         B         B        46     10309   
2        12.0       1968   0.049637         B         B        34      7759   
3        17.0       1977   0.437885         B         B        23      5735   
4        12.0       1976   0.012339         B         B        35      5776   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         5           NaN            0       11       B  184966.930730  
1         1         240.0            1       16       B  300009.450063  
2         0         229.0            1        3       B  220925.908524  
3         3        1084.0            0        5       B  175616.227217  
4         1        2078.0            2        4       B  150226.531644

In [259]:
categorical_columns = [c for c in data.columns if data[c].dtype.name == 'object']
numerical_columns   = [c for c in data.columns if data[c].dtype.name != 'object']
print (categorical_columns)
print (numerical_columns)

['Ecology_2', 'Ecology_3', 'Shops_2']
['Id', 'DistrictId', 'Rooms', 'Square', 'LifeSquare', 'KitchenSquare', 'Floor', 'HouseFloor', 'HouseYear', 'Ecology_1', 'Social_1', 'Social_2', 'Social_3', 'Healthcare_1', 'Helthcare_2', 'Shops_1', 'Price']


In [260]:
data.count(axis=0)

Id               10000
DistrictId       10000
Rooms            10000
Square           10000
LifeSquare        7887
KitchenSquare    10000
Floor            10000
HouseFloor       10000
HouseYear        10000
Ecology_1        10000
Ecology_2        10000
Ecology_3        10000
Social_1         10000
Social_2         10000
Social_3         10000
Healthcare_1      5202
Helthcare_2      10000
Shops_1          10000
Shops_2          10000
Price            10000
dtype: int64

In [261]:
data = data.fillna(data.median(axis=0), axis=0)

In [262]:
data.count(axis=0)

Id               10000
DistrictId       10000
Rooms            10000
Square           10000
LifeSquare       10000
KitchenSquare    10000
Floor            10000
HouseFloor       10000
HouseYear        10000
Ecology_1        10000
Ecology_2        10000
Ecology_3        10000
Social_1         10000
Social_2         10000
Social_3         10000
Healthcare_1     10000
Helthcare_2      10000
Shops_1          10000
Shops_2          10000
Price            10000
dtype: int64

In [263]:
data_describe = data.describe(include=[object])
data_describe
binary_columns    = [c for c in categorical_columns if data_describe[c]['unique'] == 2]
nonbinary_columns = [c for c in categorical_columns if data_describe[c]['unique'] > 2]
print (binary_columns, nonbinary_columns)

['Ecology_2', 'Ecology_3', 'Shops_2'] []


In [448]:
for c in binary_columns[1:]:
    top = data_describe[c]['top']
    top_items = data[c] == top
    data.loc[top_items, c] = 0
    data.loc[np.logical_not(top_items), c] = 1

In [267]:
data[binary_columns].describe()

Ecology_2     Ecology_3       Shops_2
count  10000.000000  10000.000000  10000.000000
mean       0.009700      0.027500      0.082500
std        0.098015      0.163543      0.275139
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000
max        1.000000      1.000000      1.000000

In [268]:
data_numerical = data[numerical_columns]
data_numerical = (data_numerical - data_numerical.mean()) / data_numerical.std()
data_numerical.describe()

Id    DistrictId         Rooms        Square    LifeSquare  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean   5.773160e-17 -7.354117e-17 -5.808687e-17  4.078737e-16 -1.084850e-14   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -1.725329e+00 -1.156311e+00 -2.251904e+00 -2.620239e+00 -4.685476e-01   
25%   -8.672342e-01 -6.974645e-01 -1.060735e+00 -6.904924e-01 -1.401729e-01   
50%    2.282827e-03 -3.303876e-01  1.304329e-01 -1.805648e-01 -4.548728e-02   
75%    8.662432e-01  5.643624e-01  1.304329e-01  4.551485e-01  6.736973e-02   
max    1.731747e+00  3.638632e+00  2.038029e+01  2.776755e+01  9.717175e+01   

       KitchenSquare         Floor    HouseFloor     HouseYear     Ecology_1  \
count   1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean    1.151010e-16  3.501643e-17 -2.519984e-16 -2.039558e-16 -3.586826e-14   
std     1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min    -2.196463e-01 -1.436078e+00 -1.860899e+00 -1.037488e-02 -9.985907e-01   
25%    -1.846334e-01 -8.636848e-01 -5.326762e-01 -1.005568e-02 -8.503276e-01   
50%    -9.569020e-03 -2.912911e-01  5.764485e-02 -1.004072e-02 -3.649128e-01   
75%     9.546962e-02  6.626983e-01  6.479659e-01 -9.921016e-03  6.462791e-01   
max     7.029630e+01  6.386635e+00  1.540599e+01  9.999000e+01  3.385916e+00   

           Social_1      Social_2      Social_3  Healthcare_1   Helthcare_2  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean  -6.164513e-18 -4.662104e-17  1.285211e-15  8.626433e-17  1.193456e-15   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -1.408062e+00 -1.293840e+00 -3.373297e-01 -1.374595e+00 -8.834356e-01   
25%   -1.065842e+00 -9.454322e-01 -3.373297e-01 -2.629820e-01 -8.834356e-01   
50%    1.785244e-02 -1.676086e-02 -2.534085e-01 -1.692315e-01 -2.139126e-01   
75%    6.452546e-01  4.679152e-01 -1.275267e-01 -4.869521e-02  4.556104e-01   
max    2.812644e+00  3.426885e+00  5.579116e+00  5.119635e+00  3.133702e+00   

            Shops_1         Price  
count  1.000000e+04  1.000000e+04  
mean  -3.351763e-16 -7.169175e-16  
std    1.000000e+00  1.000000e+00  
min   -8.803579e-01 -1.668572e+00  
25%   -6.722994e-01 -6.489150e-01  
50%   -2.561824e-01 -2.354762e-01  
75%    3.679931e-01  3.768250e-01  
max    3.904987e+00  4.512590e+00

In [293]:
data = pd.concat((data_numerical, data[binary_columns]), axis=1)
data = pd.DataFrame(data, dtype=float)
print (data.shape)
print (data.columns)

(10000, 20)
Index(['Id', 'DistrictId', 'Rooms', 'Square', 'LifeSquare', 'KitchenSquare',
       'Floor', 'HouseFloor', 'HouseYear', 'Ecology_1', 'Social_1', 'Social_2',
       'Social_3', 'Healthcare_1', 'Helthcare_2', 'Shops_1', 'Price',
       'Ecology_2', 'Ecology_3', 'Shops_2'],
      dtype='object')


In [450]:
fts = ['Square', 'Rooms','Square','HouseFloor','DistrictId', 'Floor','Shops_1',
       'Social_1', 'Social_2',
       'Social_3']
X = data.loc[:, fts]
y = data['Price']

In [451]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=11)

In [452]:
from sklearn.ensemble import RandomForestRegressor as RF

rf = RF(n_estimators=20, max_depth=10, min_samples_leaf=2, random_state=42)

In [453]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=2, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [454]:
pred = rf.predict(X_train)

In [455]:
pred

array([ 0.5752549 ,  0.20775902, -0.26085305, ..., -0.52128753,
       -0.7116104 , -0.16025895])

In [456]:
r2(y_train, pred)

0.8206721192170889

In [457]:
pred_valid = rf.predict(X_test)

In [458]:
pred_valid

array([-0.54213328, -0.66420139, -0.46755009, ...,  0.19059092,
       -0.55013113, -0.47681023])

In [459]:
r2(y_test, pred_valid)

0.7324978588500186

## Предсказания на тесте

In [460]:
test = pd.read_csv('test.csv')

In [461]:
test.shape

(5000, 19)

In [462]:
test.head()

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
0    725          58    2.0  49.882643   33.432782            6.0      6   
1  15856          74    2.0  69.263183         NaN            1.0      6   
2   5480         190    1.0  13.597819   15.948246           12.0      2   
3  15664          47    2.0  73.046609   51.940842            9.0     22   
4  14275          27    1.0  47.527111   43.387569            1.0     17   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        14.0       1972   0.310199         B         B        11      2748   
1         1.0       1977   0.075779         B         B         6      1437   
2         5.0       1909   0.000000         B         B        30      7538   
3        22.0       2007   0.101872         B         B        23      4583   
4        17.0       2017   0.072158         B         B         2       629   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  
0         1           NaN            0        0       B  
1         3           NaN            0        2       B  
2        87        4702.0            5        5       B  
3         3           NaN            3        3       B  
4         1           NaN            0        0       A

In [463]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
Id               5000 non-null int64
DistrictId       5000 non-null int64
Rooms            5000 non-null float64
Square           5000 non-null float64
LifeSquare       3959 non-null float64
KitchenSquare    5000 non-null float64
Floor            5000 non-null int64
HouseFloor       5000 non-null float64
HouseYear        5000 non-null int64
Ecology_1        5000 non-null float64
Ecology_2        5000 non-null object
Ecology_3        5000 non-null object
Social_1         5000 non-null int64
Social_2         5000 non-null int64
Social_3         5000 non-null int64
Healthcare_1     2623 non-null float64
Helthcare_2      5000 non-null int64
Shops_1          5000 non-null int64
Shops_2          5000 non-null object
dtypes: float64(7), int64(9), object(3)
memory usage: 742.3+ KB


In [464]:
categorical_columns = [c for c in data.columns if data[c].dtype.name == 'object']
numerical_columns   = [c for c in data.columns if data[c].dtype.name != 'object']
print (categorical_columns)
print (numerical_columns)

[]
['Id', 'DistrictId', 'Rooms', 'Square', 'LifeSquare', 'KitchenSquare', 'Floor', 'HouseFloor', 'HouseYear', 'Ecology_1', 'Social_1', 'Social_2', 'Social_3', 'Healthcare_1', 'Helthcare_2', 'Shops_1', 'Price', 'Ecology_2', 'Ecology_3', 'Shops_2']


In [465]:
test.count(axis=0)

Id               5000
DistrictId       5000
Rooms            5000
Square           5000
LifeSquare       3959
KitchenSquare    5000
Floor            5000
HouseFloor       5000
HouseYear        5000
Ecology_1        5000
Ecology_2        5000
Ecology_3        5000
Social_1         5000
Social_2         5000
Social_3         5000
Healthcare_1     2623
Helthcare_2      5000
Shops_1          5000
Shops_2          5000
dtype: int64

In [466]:
test = test.fillna(test.median(axis=0), axis=0)

In [467]:
test.count(axis=0)

Id               5000
DistrictId       5000
Rooms            5000
Square           5000
LifeSquare       5000
KitchenSquare    5000
Floor            5000
HouseFloor       5000
HouseYear        5000
Ecology_1        5000
Ecology_2        5000
Ecology_3        5000
Social_1         5000
Social_2         5000
Social_3         5000
Healthcare_1     5000
Helthcare_2      5000
Shops_1          5000
Shops_2          5000
dtype: int64

In [468]:
pred_test = rf.predict(test.loc[:, fts])
pred_test

array([1.10794138, 1.45930164, 0.66118523, ..., 1.04700135, 1.46597252,
       0.95118463])

In [469]:
pred_test.shape

(5000,)

In [470]:
test['Price'] = pred_test

In [471]:
test.head()

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
0    725          58    2.0  49.882643   33.432782            6.0      6   
1  15856          74    2.0  69.263183   32.925087            1.0      6   
2   5480         190    1.0  13.597819   15.948246           12.0      2   
3  15664          47    2.0  73.046609   51.940842            9.0     22   
4  14275          27    1.0  47.527111   43.387569            1.0     17   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        14.0       1972   0.310199         B         B        11      2748   
1         1.0       1977   0.075779         B         B         6      1437   
2         5.0       1909   0.000000         B         B        30      7538   
3        22.0       2007   0.101872         B         B        23      4583   
4        17.0       2017   0.072158         B         B         2       629   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2     Price  
0         1         900.0            0        0       B  1.107941  
1         3         900.0            0        2       B  1.459302  
2        87        4702.0            5        5       B  0.661185  
3         3         900.0            3        3       B  1.258893  
4         1         900.0            0        0       A  0.726871

In [474]:
test.loc[:, ['Id', 'Price']].to_csv('EReukova_predictions.csv', index=None)